-- MySQL Script generated by MySQL Workbench
-- Mon 16 Oct 2017 11:58:25 AM ICT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema churn_dw
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `churn_dw` ;

-- -----------------------------------------------------
-- Schema churn_dw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `churn_dw` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `churn_dw` ;

-- -----------------------------------------------------
-- Table `churn_dw`.`t_region_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `churn_dw`.`t_region_state` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `churn_dw`.`t_region_state` (
  `id` INT NOT NULL,
  `region` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `state_full_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `churn_dw`.`t_calls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `churn_dw`.`t_calls` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `churn_dw`.`t_calls` (
  `id` INT NOT NULL,
  `total_day_calls` VARCHAR(45) NULL,
  `total_night_calls` VARCHAR(45) NULL,
  `number_customer_service_calls` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `churn_dw`.`t_call_duration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `churn_dw`.`t_call_duration` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `churn_dw`.`t_call_duration` (
  `id` INT NOT NULL,
  `total_day_minutes` VARCHAR(20) NULL,
  `total_eve_minutes` VARCHAR(45) NULL,
  `total_night_minutes` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `churn_dw`.`t_charge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `churn_dw`.`t_charge` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `churn_dw`.`t_charge` (
  `id` INT NOT NULL,
  `total_day_charges` VARCHAR(45) NULL,
  `total_eve_charges` VARCHAR(45) NULL,
  `total_night_charges` VARCHAR(45) NULL,
  `total_intl_charges` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `churn_dw`.`t_fact_churn`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `churn_dw`.`t_fact_churn` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `churn_dw`.`t_fact_churn` (
  `id` INT NOT NULL,
  `areacode_phonenumber` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_t_region_state_id`
    FOREIGN KEY (`id`)
    REFERENCES `churn_dw`.`t_region_state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_calls_id`
    FOREIGN KEY (`id`)
    REFERENCES `churn_dw`.`t_calls` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_call_duration_id`
    FOREIGN KEY (`id`)
    REFERENCES `churn_dw`.`t_call_duration` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_charge_id`
    FOREIGN KEY (`id`)
    REFERENCES `churn_dw`.`t_charge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
